import { resolve } from "node:path";

import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: {
      "@engine": resolve(import.meta.dirname, "packages/engine/src"),
    },
  },
  test: {
    globals: true,
    include: ["packages/*/src/**/*.test.{ts,tsx}"],
    // Renderer tests opt into a DOM with a `// @vitest-environment jsdom` comment;
    // everything else stays on the faster node environment.
    restoreMocks: true,
    unstubGlobals: true,
    coverage: {
      provider: "v8",
      include: ["packages/*/src/**/*.{ts,tsx}"],
      exclude: [
        "**/*.test.{ts,tsx}",
        "**/*.d.ts",
        // Generated by Peggy from arithmetic.pegjs.
        "packages/engine/src/parser/arithmetic*.js",
      ],
      reporter: ["text-summary", "html"],
    },
  },
});
