import type { ASTNode } from "../ast.js";

// Pre-compiled parser (generated by: npx peggy --format es -o arithmetic-parser.js arithmetic.pegjs)
import { parse as pegParse } from "./arithmetic-parser.js";

export interface ParseOptions {
  knownUnits?: Set<string>;
  knownFunctions?: Set<string>;
  knownConstants?: Set<string>;
  knownDateLiterals?: Set<string>;
  knownLineRefs?: Set<string>;
  knownBaseKeywords?: Set<string>;
}

export function parse(input: string, options?: ParseOptions): ASTNode {
  return pegParse(input, options) as ASTNode;
}
