import type { PluginManifest } from "../types.js";

/**
 * Common timezone abbreviations → IANA identifiers.
 * These are registered alongside city names so users can type "now in EST" etc.
 */
const ABBREVIATIONS: Record<string, string> = {
  // Universal
  UTC: "UTC",
  GMT: "Etc/GMT",

  // North America
  EST: "America/New_York",
  EDT: "America/New_York",
  CST: "America/Chicago",
  CDT: "America/Chicago",
  MST: "America/Denver",
  MDT: "America/Denver",
  PST: "America/Los_Angeles",
  PDT: "America/Los_Angeles",
  AKST: "America/Anchorage",
  AKDT: "America/Anchorage",
  HST: "Pacific/Honolulu",

  // South America
  BRT: "America/Sao_Paulo",
  BRST: "America/Sao_Paulo",
  ART: "America/Argentina/Buenos_Aires",
  CLT: "America/Santiago",
  CLST: "America/Santiago",
  COT: "America/Bogota",
  PET: "America/Lima",
  VET: "America/Caracas",
  BOT: "America/La_Paz",
  PYT: "America/Asuncion",
  UYT: "America/Montevideo",

  // Europe
  WET: "Europe/Lisbon",
  WEST: "Europe/Lisbon",
  CET: "Europe/Paris",
  CEST: "Europe/Paris",
  EET: "Europe/Athens",
  EEST: "Europe/Athens",
  MSK: "Europe/Moscow",
  TRT: "Europe/Istanbul",

  // Middle East
  IRST: "Asia/Tehran",

  // Asia
  PKT: "Asia/Karachi",
  IST: "Asia/Kolkata",
  NPT: "Asia/Katmandu",
  ICT: "Asia/Bangkok",
  WIB: "Asia/Jakarta",
  WITA: "Asia/Makassar",
  WIT: "Asia/Jayapura",
  SGT: "Asia/Singapore",
  MYT: "Asia/Kuala_Lumpur",
  PHT: "Asia/Manila",
  HKT: "Asia/Hong_Kong",
  JST: "Asia/Tokyo",
  KST: "Asia/Seoul",

  // Australia & Pacific
  AWST: "Australia/Perth",
  ACST: "Australia/Adelaide",
  ACDT: "Australia/Adelaide",
  AEST: "Australia/Sydney",
  AEDT: "Australia/Sydney",
  NZST: "Pacific/Auckland",
  NZDT: "Pacific/Auckland",
  FJT: "Pacific/Fiji",

  // Africa
  WAT: "Africa/Lagos",
  CAT: "Africa/Harare",
  EAT: "Africa/Nairobi",
  SAST: "Africa/Johannesburg",
};

/**
 * All IANA tz database zones, keyed by city/region name.
 * Generated from Intl.supportedValuesOf('timeZone').
 * Hyphens are replaced with underscores for parser compatibility.
 */
const IANA_ZONES: Record<string, string> = {
  Abidjan: "Africa/Abidjan",
  Accra: "Africa/Accra",
  Addis_Ababa: "Africa/Addis_Ababa",
  Algiers: "Africa/Algiers",
  Asmera: "Africa/Asmera",
  Bamako: "Africa/Bamako",
  Bangui: "Africa/Bangui",
  Banjul: "Africa/Banjul",
  Bissau: "Africa/Bissau",
  Blantyre: "Africa/Blantyre",
  Brazzaville: "Africa/Brazzaville",
  Bujumbura: "Africa/Bujumbura",
  Cairo: "Africa/Cairo",
  Casablanca: "Africa/Casablanca",
  Ceuta: "Africa/Ceuta",
  Conakry: "Africa/Conakry",
  Dakar: "Africa/Dakar",
  Dar_es_Salaam: "Africa/Dar_es_Salaam",
  Djibouti: "Africa/Djibouti",
  Douala: "Africa/Douala",
  El_Aaiun: "Africa/El_Aaiun",
  Freetown: "Africa/Freetown",
  Gaborone: "Africa/Gaborone",
  Harare: "Africa/Harare",
  Johannesburg: "Africa/Johannesburg",
  Juba: "Africa/Juba",
  Kampala: "Africa/Kampala",
  Khartoum: "Africa/Khartoum",
  Kigali: "Africa/Kigali",
  Kinshasa: "Africa/Kinshasa",
  Lagos: "Africa/Lagos",
  Libreville: "Africa/Libreville",
  Lome: "Africa/Lome",
  Luanda: "Africa/Luanda",
  Lubumbashi: "Africa/Lubumbashi",
  Lusaka: "Africa/Lusaka",
  Malabo: "Africa/Malabo",
  Maputo: "Africa/Maputo",
  Maseru: "Africa/Maseru",
  Mbabane: "Africa/Mbabane",
  Mogadishu: "Africa/Mogadishu",
  Monrovia: "Africa/Monrovia",
  Nairobi: "Africa/Nairobi",
  Ndjamena: "Africa/Ndjamena",
  Niamey: "Africa/Niamey",
  Nouakchott: "Africa/Nouakchott",
  Ouagadougou: "Africa/Ouagadougou",
  Porto_Novo: "Africa/Porto-Novo",
  Sao_Tome: "Africa/Sao_Tome",
  Tripoli: "Africa/Tripoli",
  Tunis: "Africa/Tunis",
  Windhoek: "Africa/Windhoek",
  Adak: "America/Adak",
  Anchorage: "America/Anchorage",
  Anguilla: "America/Anguilla",
  Antigua: "America/Antigua",
  Araguaina: "America/Araguaina",
  La_Rioja: "America/Argentina/La_Rioja",
  Rio_Gallegos: "America/Argentina/Rio_Gallegos",
  Salta: "America/Argentina/Salta",
  San_Juan: "America/Argentina/San_Juan",
  San_Luis: "America/Argentina/San_Luis",
  Tucuman: "America/Argentina/Tucuman",
  Ushuaia: "America/Argentina/Ushuaia",
  Aruba: "America/Aruba",
  Asuncion: "America/Asuncion",
  Bahia: "America/Bahia",
  Bahia_Banderas: "America/Bahia_Banderas",
  Barbados: "America/Barbados",
  Belem: "America/Belem",
  Belize: "America/Belize",
  Blanc_Sablon: "America/Blanc-Sablon",
  Boa_Vista: "America/Boa_Vista",
  Bogota: "America/Bogota",
  Boise: "America/Boise",
  Buenos_Aires: "America/Buenos_Aires",
  Cambridge_Bay: "America/Cambridge_Bay",
  Campo_Grande: "America/Campo_Grande",
  Cancun: "America/Cancun",
  Caracas: "America/Caracas",
  Catamarca: "America/Catamarca",
  Cayenne: "America/Cayenne",
  Cayman: "America/Cayman",
  Chicago: "America/Chicago",
  Chihuahua: "America/Chihuahua",
  Ciudad_Juarez: "America/Ciudad_Juarez",
  Coral_Harbour: "America/Coral_Harbour",
  Cordoba: "America/Cordoba",
  Costa_Rica: "America/Costa_Rica",
  Coyhaique: "America/Coyhaique",
  Creston: "America/Creston",
  Cuiaba: "America/Cuiaba",
  Curacao: "America/Curacao",
  Danmarkshavn: "America/Danmarkshavn",
  Dawson: "America/Dawson",
  Dawson_Creek: "America/Dawson_Creek",
  Denver: "America/Denver",
  Detroit: "America/Detroit",
  Dominica: "America/Dominica",
  Edmonton: "America/Edmonton",
  Eirunepe: "America/Eirunepe",
  El_Salvador: "America/El_Salvador",
  Fort_Nelson: "America/Fort_Nelson",
  Fortaleza: "America/Fortaleza",
  Glace_Bay: "America/Glace_Bay",
  Godthab: "America/Godthab",
  Goose_Bay: "America/Goose_Bay",
  Grand_Turk: "America/Grand_Turk",
  Grenada: "America/Grenada",
  Guadeloupe: "America/Guadeloupe",
  Guatemala: "America/Guatemala",
  Guayaquil: "America/Guayaquil",
  Guyana: "America/Guyana",
  Halifax: "America/Halifax",
  Havana: "America/Havana",
  Hermosillo: "America/Hermosillo",
  Knox: "America/Indiana/Knox",
  Marengo: "America/Indiana/Marengo",
  Petersburg: "America/Indiana/Petersburg",
  Tell_City: "America/Indiana/Tell_City",
  Vevay: "America/Indiana/Vevay",
  Vincennes: "America/Indiana/Vincennes",
  Winamac: "America/Indiana/Winamac",
  Indianapolis: "America/Indianapolis",
  Inuvik: "America/Inuvik",
  Iqaluit: "America/Iqaluit",
  Jamaica: "America/Jamaica",
  Jujuy: "America/Jujuy",
  Juneau: "America/Juneau",
  Monticello: "America/Kentucky/Monticello",
  Kralendijk: "America/Kralendijk",
  La_Paz: "America/La_Paz",
  Lima: "America/Lima",
  Los_Angeles: "America/Los_Angeles",
  Louisville: "America/Louisville",
  Lower_Princes: "America/Lower_Princes",
  Maceio: "America/Maceio",
  Managua: "America/Managua",
  Manaus: "America/Manaus",
  Marigot: "America/Marigot",
  Martinique: "America/Martinique",
  Matamoros: "America/Matamoros",
  Mazatlan: "America/Mazatlan",
  Mendoza: "America/Mendoza",
  Menominee: "America/Menominee",
  Merida: "America/Merida",
  Metlakatla: "America/Metlakatla",
  Mexico_City: "America/Mexico_City",
  Miquelon: "America/Miquelon",
  Moncton: "America/Moncton",
  Monterrey: "America/Monterrey",
  Montevideo: "America/Montevideo",
  Montserrat: "America/Montserrat",
  Nassau: "America/Nassau",
  New_York: "America/New_York",
  Nome: "America/Nome",
  Noronha: "America/Noronha",
  Beulah: "America/North_Dakota/Beulah",
  Center: "America/North_Dakota/Center",
  New_Salem: "America/North_Dakota/New_Salem",
  Ojinaga: "America/Ojinaga",
  Panama: "America/Panama",
  Paramaribo: "America/Paramaribo",
  Phoenix: "America/Phoenix",
  Port_au_Prince: "America/Port-au-Prince",
  Port_of_Spain: "America/Port_of_Spain",
  Porto_Velho: "America/Porto_Velho",
  Puerto_Rico: "America/Puerto_Rico",
  Punta_Arenas: "America/Punta_Arenas",
  Rankin_Inlet: "America/Rankin_Inlet",
  Recife: "America/Recife",
  Regina: "America/Regina",
  Resolute: "America/Resolute",
  Rio_Branco: "America/Rio_Branco",
  Santarem: "America/Santarem",
  Santiago: "America/Santiago",
  Santo_Domingo: "America/Santo_Domingo",
  Sao_Paulo: "America/Sao_Paulo",
  Scoresbysund: "America/Scoresbysund",
  Sitka: "America/Sitka",
  St_Barthelemy: "America/St_Barthelemy",
  St_Johns: "America/St_Johns",
  St_Kitts: "America/St_Kitts",
  St_Lucia: "America/St_Lucia",
  St_Thomas: "America/St_Thomas",
  St_Vincent: "America/St_Vincent",
  Swift_Current: "America/Swift_Current",
  Tegucigalpa: "America/Tegucigalpa",
  Thule: "America/Thule",
  Tijuana: "America/Tijuana",
  Toronto: "America/Toronto",
  Tortola: "America/Tortola",
  Vancouver: "America/Vancouver",
  Whitehorse: "America/Whitehorse",
  Winnipeg: "America/Winnipeg",
  Yakutat: "America/Yakutat",
  Casey: "Antarctica/Casey",
  Davis: "Antarctica/Davis",
  DumontDUrville: "Antarctica/DumontDUrville",
  Macquarie: "Antarctica/Macquarie",
  Mawson: "Antarctica/Mawson",
  McMurdo: "Antarctica/McMurdo",
  Palmer: "Antarctica/Palmer",
  Rothera: "Antarctica/Rothera",
  Syowa: "Antarctica/Syowa",
  Troll: "Antarctica/Troll",
  Vostok: "Antarctica/Vostok",
  Longyearbyen: "Arctic/Longyearbyen",
  Aden: "Asia/Aden",
  Almaty: "Asia/Almaty",
  Amman: "Asia/Amman",
  Anadyr: "Asia/Anadyr",
  Aqtau: "Asia/Aqtau",
  Aqtobe: "Asia/Aqtobe",
  Ashgabat: "Asia/Ashgabat",
  Atyrau: "Asia/Atyrau",
  Baghdad: "Asia/Baghdad",
  Bahrain: "Asia/Bahrain",
  Baku: "Asia/Baku",
  Bangkok: "Asia/Bangkok",
  Barnaul: "Asia/Barnaul",
  Beirut: "Asia/Beirut",
  Bishkek: "Asia/Bishkek",
  Brunei: "Asia/Brunei",
  Calcutta: "Asia/Calcutta",
  Chita: "Asia/Chita",
  Colombo: "Asia/Colombo",
  Damascus: "Asia/Damascus",
  Dhaka: "Asia/Dhaka",
  Dili: "Asia/Dili",
  Dubai: "Asia/Dubai",
  Dushanbe: "Asia/Dushanbe",
  Famagusta: "Asia/Famagusta",
  Gaza: "Asia/Gaza",
  Hebron: "Asia/Hebron",
  Hong_Kong: "Asia/Hong_Kong",
  Hovd: "Asia/Hovd",
  Irkutsk: "Asia/Irkutsk",
  Jakarta: "Asia/Jakarta",
  Jayapura: "Asia/Jayapura",
  Jerusalem: "Asia/Jerusalem",
  Kabul: "Asia/Kabul",
  Kamchatka: "Asia/Kamchatka",
  Karachi: "Asia/Karachi",
  Katmandu: "Asia/Katmandu",
  Khandyga: "Asia/Khandyga",
  Krasnoyarsk: "Asia/Krasnoyarsk",
  Kuala_Lumpur: "Asia/Kuala_Lumpur",
  Kuching: "Asia/Kuching",
  Kuwait: "Asia/Kuwait",
  Macau: "Asia/Macau",
  Magadan: "Asia/Magadan",
  Makassar: "Asia/Makassar",
  Manila: "Asia/Manila",
  Muscat: "Asia/Muscat",
  Nicosia: "Asia/Nicosia",
  Novokuznetsk: "Asia/Novokuznetsk",
  Novosibirsk: "Asia/Novosibirsk",
  Omsk: "Asia/Omsk",
  Oral: "Asia/Oral",
  Phnom_Penh: "Asia/Phnom_Penh",
  Pontianak: "Asia/Pontianak",
  Pyongyang: "Asia/Pyongyang",
  Qatar: "Asia/Qatar",
  Qostanay: "Asia/Qostanay",
  Qyzylorda: "Asia/Qyzylorda",
  Rangoon: "Asia/Rangoon",
  Riyadh: "Asia/Riyadh",
  Saigon: "Asia/Saigon",
  Sakhalin: "Asia/Sakhalin",
  Samarkand: "Asia/Samarkand",
  Seoul: "Asia/Seoul",
  Shanghai: "Asia/Shanghai",
  Singapore: "Asia/Singapore",
  Srednekolymsk: "Asia/Srednekolymsk",
  Taipei: "Asia/Taipei",
  Tashkent: "Asia/Tashkent",
  Tbilisi: "Asia/Tbilisi",
  Tehran: "Asia/Tehran",
  Thimphu: "Asia/Thimphu",
  Tokyo: "Asia/Tokyo",
  Tomsk: "Asia/Tomsk",
  Ulaanbaatar: "Asia/Ulaanbaatar",
  Urumqi: "Asia/Urumqi",
  Ust_Nera: "Asia/Ust-Nera",
  Vientiane: "Asia/Vientiane",
  Vladivostok: "Asia/Vladivostok",
  Yakutsk: "Asia/Yakutsk",
  Yekaterinburg: "Asia/Yekaterinburg",
  Yerevan: "Asia/Yerevan",
  Azores: "Atlantic/Azores",
  Bermuda: "Atlantic/Bermuda",
  Canary: "Atlantic/Canary",
  Cape_Verde: "Atlantic/Cape_Verde",
  Faeroe: "Atlantic/Faeroe",
  Madeira: "Atlantic/Madeira",
  Reykjavik: "Atlantic/Reykjavik",
  South_Georgia: "Atlantic/South_Georgia",
  St_Helena: "Atlantic/St_Helena",
  Stanley: "Atlantic/Stanley",
  Adelaide: "Australia/Adelaide",
  Brisbane: "Australia/Brisbane",
  Broken_Hill: "Australia/Broken_Hill",
  Darwin: "Australia/Darwin",
  Eucla: "Australia/Eucla",
  Hobart: "Australia/Hobart",
  Lindeman: "Australia/Lindeman",
  Lord_Howe: "Australia/Lord_Howe",
  Melbourne: "Australia/Melbourne",
  Perth: "Australia/Perth",
  Sydney: "Australia/Sydney",
  Amsterdam: "Europe/Amsterdam",
  Andorra: "Europe/Andorra",
  Astrakhan: "Europe/Astrakhan",
  Athens: "Europe/Athens",
  Belgrade: "Europe/Belgrade",
  Berlin: "Europe/Berlin",
  Bratislava: "Europe/Bratislava",
  Brussels: "Europe/Brussels",
  Bucharest: "Europe/Bucharest",
  Budapest: "Europe/Budapest",
  Busingen: "Europe/Busingen",
  Chisinau: "Europe/Chisinau",
  Copenhagen: "Europe/Copenhagen",
  Dublin: "Europe/Dublin",
  Gibraltar: "Europe/Gibraltar",
  Guernsey: "Europe/Guernsey",
  Helsinki: "Europe/Helsinki",
  Isle_of_Man: "Europe/Isle_of_Man",
  Istanbul: "Europe/Istanbul",
  Jersey: "Europe/Jersey",
  Kaliningrad: "Europe/Kaliningrad",
  Kiev: "Europe/Kiev",
  Kirov: "Europe/Kirov",
  Lisbon: "Europe/Lisbon",
  Ljubljana: "Europe/Ljubljana",
  London: "Europe/London",
  Luxembourg: "Europe/Luxembourg",
  Madrid: "Europe/Madrid",
  Malta: "Europe/Malta",
  Mariehamn: "Europe/Mariehamn",
  Minsk: "Europe/Minsk",
  Monaco: "Europe/Monaco",
  Moscow: "Europe/Moscow",
  Oslo: "Europe/Oslo",
  Paris: "Europe/Paris",
  Podgorica: "Europe/Podgorica",
  Prague: "Europe/Prague",
  Riga: "Europe/Riga",
  Rome: "Europe/Rome",
  Samara: "Europe/Samara",
  San_Marino: "Europe/San_Marino",
  Sarajevo: "Europe/Sarajevo",
  Saratov: "Europe/Saratov",
  Simferopol: "Europe/Simferopol",
  Skopje: "Europe/Skopje",
  Sofia: "Europe/Sofia",
  Stockholm: "Europe/Stockholm",
  Tallinn: "Europe/Tallinn",
  Tirane: "Europe/Tirane",
  Ulyanovsk: "Europe/Ulyanovsk",
  Vaduz: "Europe/Vaduz",
  Vatican: "Europe/Vatican",
  Vienna: "Europe/Vienna",
  Vilnius: "Europe/Vilnius",
  Volgograd: "Europe/Volgograd",
  Warsaw: "Europe/Warsaw",
  Zagreb: "Europe/Zagreb",
  Zurich: "Europe/Zurich",
  Antananarivo: "Indian/Antananarivo",
  Chagos: "Indian/Chagos",
  Christmas: "Indian/Christmas",
  Cocos: "Indian/Cocos",
  Comoro: "Indian/Comoro",
  Kerguelen: "Indian/Kerguelen",
  Mahe: "Indian/Mahe",
  Maldives: "Indian/Maldives",
  Mauritius: "Indian/Mauritius",
  Mayotte: "Indian/Mayotte",
  Reunion: "Indian/Reunion",
  Apia: "Pacific/Apia",
  Auckland: "Pacific/Auckland",
  Bougainville: "Pacific/Bougainville",
  Chatham: "Pacific/Chatham",
  Easter: "Pacific/Easter",
  Efate: "Pacific/Efate",
  Enderbury: "Pacific/Enderbury",
  Fakaofo: "Pacific/Fakaofo",
  Fiji: "Pacific/Fiji",
  Funafuti: "Pacific/Funafuti",
  Galapagos: "Pacific/Galapagos",
  Gambier: "Pacific/Gambier",
  Guadalcanal: "Pacific/Guadalcanal",
  Guam: "Pacific/Guam",
  Honolulu: "Pacific/Honolulu",
  Kiritimati: "Pacific/Kiritimati",
  Kosrae: "Pacific/Kosrae",
  Kwajalein: "Pacific/Kwajalein",
  Majuro: "Pacific/Majuro",
  Marquesas: "Pacific/Marquesas",
  Midway: "Pacific/Midway",
  Nauru: "Pacific/Nauru",
  Niue: "Pacific/Niue",
  Norfolk: "Pacific/Norfolk",
  Noumea: "Pacific/Noumea",
  Pago_Pago: "Pacific/Pago_Pago",
  Palau: "Pacific/Palau",
  Pitcairn: "Pacific/Pitcairn",
  Ponape: "Pacific/Ponape",
  Port_Moresby: "Pacific/Port_Moresby",
  Rarotonga: "Pacific/Rarotonga",
  Saipan: "Pacific/Saipan",
  Tahiti: "Pacific/Tahiti",
  Tarawa: "Pacific/Tarawa",
  Tongatapu: "Pacific/Tongatapu",
  Truk: "Pacific/Truk",
  Wake: "Pacific/Wake",
  Wallis: "Pacific/Wallis",
};

function formatDateInTimezone(timestamp: number, iana: string): string {
  const date = new Date(timestamp);
  return new Intl.DateTimeFormat("en-US", {
    weekday: "short",
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
    timeZone: iana,
    timeZoneName: "short",
  }).format(date);
}

function buildBaseConversions(): PluginManifest["baseConversions"] {
  const conversions: NonNullable<PluginManifest["baseConversions"]> = {};

  function register(keyword: string, iana: string): void {
    const entry = {
      formatter: (n: number) => formatDateInTimezone(n, iana),
      detail: `timezone: ${iana}`,
      category: "date" as const,
    };
    conversions[keyword] = entry;
    // Also register lowercase variant for case-insensitive matching
    const lower = keyword.toLowerCase();
    if (lower !== keyword) {
      conversions[lower] = entry;
    }
  }

  // Register abbreviations (UTC, EST, PST, BRT, JST, etc.)
  for (const [abbr, iana] of Object.entries(ABBREVIATIONS)) {
    register(abbr, iana);
  }

  // Register all IANA city/region names
  for (const [city, iana] of Object.entries(IANA_ZONES)) {
    register(city, iana);
  }

  return conversions;
}

export const timezonePlugin: PluginManifest = {
  id: "core.timezone",
  name: "Timezone Conversion",
  description:
    "Convert date/time values between timezones using abbreviations (UTC, EST, BRT, JST) " +
    "or city names from the IANA tz database (Tokyo, London, Sao_Paulo, New_York, etc.)",
  baseConversions: buildBaseConversions(),
  tests: [
    {
      description: "now in UTC shows date with timezone",
      input: "now in UTC",
      tolerance: Date.now(),
    },
    {
      description: "today in BRT shows date with timezone",
      input: "today in BRT",
      tolerance: Date.now(),
    },
    {
      description: "today in Tokyo shows date with timezone",
      input: "today in Tokyo",
      tolerance: Date.now(),
    },
    {
      description: "today in New_York shows date with timezone",
      input: "today in New_York",
      tolerance: Date.now(),
    },
    {
      description: "now in Sao_Paulo shows date with timezone",
      input: "now in Sao_Paulo",
      tolerance: Date.now(),
    },
  ],
  help: [
    {
      title: "Timezones",
      description:
        "Convert dates to different timezones with in or to. " +
        "Supports abbreviations (UTC, EST, BRT, JST) and 400+ IANA city names (Tokyo, London, Sao_Paulo). " +
        "Full list: en.wikipedia.org/wiki/List_of_tz_database_time_zones",
      examples: [
        { input: "now in UTC", output: "time in UTC" },
        { input: "today in Tokyo", output: "time in Tokyo" },
        { input: "now in BRT", output: "time in Brazil" },
        { input: "tomorrow in New_York", output: "time in NY" },
        { input: "now in London", output: "time in London" },
        { input: "today in Sao_Paulo", output: "time in SP" },
      ],
    },
  ],
};
